#spring:
#  kafka:
#    consumer:
#      properties:
#        spring.json.trusted.packages: com.example.kafkaexample.model.*
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer